Adding troubleshooting guide for BOMs
mcode/mcode-extraction-framework pull request #112
Opened 2021-04-23 18:11 UTC by dmendelowitz

# Summary
Added section to README informing users that byte order markers are handled for UTF-8 and UTF-16 but may cause issues in other encodings and how they can check for BOMs in their CSVs
# Testing guidance
Read the new section of the README and make sure it is all correct and that I didn't leave anything out

2021-04-26 12:21 UTC, julianxcarter requested changes
The here text looks good! I just had two minor comments.

2021-04-26 12:21 UTC, julianxcarter commented on README.md
> +cat -v file.csv
I think we should write the example code as `cat -v <path-to-csv>` or `cat -v <file.csv>`. We've been including example values within the `<` and `>` brackets as a general practice in our READMEs.

2021-04-26 12:21 UTC, julianxcarter commented on README.md
> +The extraction client has built-in handling of byte order markers for CSV files in UTF-8 and UTF-16 encodings. When using CSV files in other encodings, if you experience unexpected errors be sure to
We should specify that we only handle UTF-16 (LE) encodings. There's actually two UTF-16 encodings (LE and BE) and the module only parses out BOMs from the LE variety.

2021-04-26 13:19 UTC, julianxcarter approved these changes
Looks great, thanks for handling that!

2021-04-26 20:15 UTC, jafeltra reviewed
I just had one really small comment. Let me know what you think.

2021-04-26 20:15 UTC, jafeltra commented on README.md
> +If there is an unexpected symbol at the beginning of the file, then there is a byte order marker that needs to be removed.
This is a little nit-picky, but can we maybe update this to say "...there may be a byte order marker that needs to be removed"? I'm guessing there could be a case where the unexpected symbol isn't necessarily a byte order marker or shouldn't be be removed.

2021-04-27 13:25 UTC, jafeltra approved these changes
Looks great!

2021-04-27 13:30 UTC, jafeltra commented
I think this might just need to be rebased again. I doubt there are any conflicts but I just want to make sure no README updates get lost!

2021-04-27 14:38 UTC, merged