Modified app.js to return object instead of writing to file; moved code to write to file to cli.js
mcode/mcode-extraction-framework pull request #126
Opened 2021-06-03 15:16 UTC by SenecaAnderson

# Summary
The function mcodeApp in src/cli/app.js was modified to return the extractedData object instead of writing the results to a file. src/cli/cli.js was modified to write the results of calling mocdeApp to a file.

## New behavior
cli.js writes the results of extraction to a file instead of app.js.

## Code changes
The code to write to a file was moved from app.js to cli.js and replaced with a return statement.

# Testing guidance
Use 'npm start' to run extraction.

2021-06-03 15:52 UTC, mgramigna requested changes

2021-06-03 15:52 UTC, mgramigna commented on src/cli/cli.js
> +    extractedData = await mcodeApp(MCODEClient, fromDate, toDate, configFilepath, runLogFilepath, debug, allEntries);
Since this is a new variable, you'll need to add a `const extractedData = ` instead so Javascript knows

2021-06-03 15:54 UTC, mgramigna commented
I see there are some linter errors being caught by Github actions here. We have a pretty strict linter set up in the MEF, which allows us to enforce code style and make sure the syntax is correct.

You can configure VS Code to show you the lint errors by installing this extension: https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint

Once you do, you should see some errors in the editor that should need to be resolved. You can also check lint locally with the npm script we've added:

```
npm run lint
```

We also have a command that will fix and automatically fixable lint issues:

```
npm run lint-fix
```

2021-06-03 16:39 UTC, mgramigna commented
Other than the lint errors and the change request I made, this looks good and works as expected

2021-06-03 17:13 UTC, mgramigna approved these changes

2021-06-04 16:51 UTC, jafeltra approved these changes
Looks great!

2021-06-04 16:52 UTC, merged