Support CSVs with blank lines and empty values
mcode/mcode-extraction-framework pull request #169
Opened 2021-12-09 14:35 UTC by Dtphelan1

# Summary

Supports ingestion of CSV's with either totally blank rows of data or rows with nothing by empty-values; in both cases those rows will be ignored. 

## New behavior

Now the CSVFileModule can ingest files with rows that meet the above criteria.

## Code changes

Some new tests

# Testing guidance

Make sure the tool still works.

2021-12-09 20:12 UTC, dmendelowitz requested changes
This looks great! Just had one small comment

2021-12-09 20:12 UTC, dmendelowitz commented on test/modules/CSVFileModule.test.js
> -const csvFileModuleWithBOMs = new CSVFileModule(path.join(__dirname, './fixtures/example-csv-bom.csv'));
I think we can delete `example-csv-bom.csv` now, right? It's not used anywhere else.

2021-12-09 20:42 UTC, jafeltra commented
I'm not officially reviewing this PR, but when I was looking through the code yesterday and when Dylan M mentioned the bom nightmares, I remembered there are two other places we probably need these option as well. There's the `CSVURLModule` and the function in `appUtils` that uses it for the patient ids CSV. I think we want this in both of those places as well, right?

2021-12-09 20:51 UTC, jafeltra commented
> I wonder if it would be worth it to write a wrapper function that just calls `parse()` with the right settings and use that in all three places just so we never have to worry about this again?

Ah that's a good point. I feel like that could definitely be worthwhile.

2021-12-10 14:52 UTC, Dtphelan1 commented on test/modules/CSVFileModule.test.js
> -const csvFileModuleWithBOMs = new CSVFileModule(path.join(__dirname, './fixtures/example-csv-bom.csv'));
We are still using it, just encapsulated it within the test that uses it instead of leaving it up at the top

2021-12-10 15:03 UTC, dmendelowitz commented on test/modules/CSVFileModule.test.js
> -const csvFileModuleWithBOMs = new CSVFileModule(path.join(__dirname, './fixtures/example-csv-bom.csv'));
Sorry if I'm missing something obvious but I don't see the file used anywhere in the tests. The BOM test uses `example-csv-empty-values.csv`, is that intentional? I think that file has a BOM so it is an accurate test

2021-12-10 15:38 UTC, Dtphelan1 commented on test/modules/CSVFileModule.test.js
> -const csvFileModuleWithBOMs = new CSVFileModule(path.join(__dirname, './fixtures/example-csv-bom.csv'));
Definitely not intentional. Definitely a typo. Fixing now.

2021-12-10 16:04 UTC, dmendelowitz approved these changes

2021-12-10 16:04 UTC, merged