CSVExtractor's now support dataDirectory & fileName arguments
mcode/mcode-extraction-framework pull request #170
Opened 2021-12-14 21:52 UTC by Dtphelan1

# Summary

CSVExtractors now support ingesting a `dataDirectory` & `fileName` argument pair, with which the extractor constructs an absolute path to a data file. This technique for specifying the location of a CSV file on disk is now the preferred method, in contrast with our previous `filePath` argument technique. Documentation, example config files, and schemas have been updated to reflect this. 

## New behavior

All CSVExtractors extending from the BaseCSVExtractor should now support the ingestion of `fileName` and `dataDirectory` arguments. The BaseCSVExtractor now considers a new case in the initial extractor construction to handle the consumption of these arguments. 

## Code changes

- Updated the README to reflect this argument pair as our preferred approach;
- Updated example config to use this approach by default;
- Updated the BaseCSVExtractor to build that absolute file path when the two arguments are provided;
- Updated the BaseCSVExtractor to throw when the `dataDirectory` is not an absolute path;
- Updated all XCSVExtractors, where X is a ResourceType, to pass the `dataDirectory` and `fileName` arguments to their `super` constructors;
- Added `BaseCSVExtractor` to the extractors exported by `MEF/src/extractors/index.js`;
- Updated the config schema to reflect new properties, adding descriptions for human readability;
- Added tests to ensure that the BaseCSVExtractor handles its argument cases appropriately, throwing when expected.

# Testing guidance
- Ensure all tests pass;
- Ensure local extraction works once you've updated your Config appropriately; 
- Ensure that the schema updates are sufficient;
- Ensure that the approach is reasonable.
- Ensure that there aren't any missed documentation updates needed

2021-12-15 17:34 UTC, julianxcarter requested changes
This looks great and I think the approach makes a lot of sense! I just have a few suggestions that I'd like your thoughts on :).

2021-12-15 17:34 UTC, julianxcarter commented on src/extractors/BaseCSVExtractor.js
> +      if (!path.isAbsolute(dataDirectory)) throw new Error('dataDirectory is not an absolutePath, it needs to be.');
Apparently, `path.isAbsolute` considers paths with a leading tilde (~) character to be a relative path. I guess this is technically correct, but it is something that I think we should allow. I'm not sure that writing our own function for checking that a path is absolute (while allowing the tilde character) is worth it, but if we decide to keep things as they are then we should change [the example dataDirectory property in csv.config.example.json](https://github.com/mcode/mcode-extraction-framework/blob/f1e2cdcfc426c32575e8fe7f2d0835b658e9c877/config/csv.config.example.json#L4) to use the `/Users/xxxxx/` paradigm instead of using a tilde.

2021-12-15 19:38 UTC, Dtphelan1 commented on README.md
> +3. For each extractor, `fileName` should correspond to the file name this extractor should be reading from. Note: combining the `dataDirectory` above and `fileName` should resolve to a file on disk c
1) I think we're find for now omitting it, since the main reason we still support `filePath` is for backwards compatability. Alternatively, we could write a note saying that if your config uses a now-deprecated `filePath` property that we will still support it, without telling new people how to use that feature. Thoughts on that middle of the road approach? 
2) Great catch on the other examples. I will change those to use fileName.

2021-12-15 19:50 UTC, Dtphelan1 commented on src/extractors/BaseCSVExtractor.js
> +      if (!path.isAbsolute(dataDirectory)) throw new Error('dataDirectory is not an absolutePath, it needs to be.');
Great catch and great suggestion!

2021-12-16 17:02 UTC, julianxcarter approved these changes

2021-12-16 19:46 UTC, merged