Passthrough csv-parse options supported in the config
mcode/mcode-extraction-framework pull request #175
Opened 2022-01-20 14:03 UTC by julianxcarter

# Summary
Adds support for a `csvParse` property within `commonExtractorArgs` of the config. Values included in the `options` property of this `csvParse` object will be passed to the `csv-parse` module as Extractors are initialized. Default options such as BOM removal and empty line skipping are still kept, but users can now override them (which is not recommended) or include their own in the event that they encounter errors while running the extractor. 
## New behavior
Properties included in the `commonExtractorArgs.csvParse.options` section of the config are passed to the `csv-parse` module to be used as the MEF reads CSV files. 
## Code changes
1. The `BaseCSVExtractor` (and each child Extractor class) now takes a `csvParse` argument in its constructor. The `BaseCSVExtractor` pulls the `options` property from this argument and passes it to the `CSVFileModule` and `CSVURLModule`.
2. References to this new config option are added to `csv.config.example.json`, `csv.schema.json`, and the README.
# Testing guidance
1. Ensure that extraction still works as expected when `commonExtractorArgs.csvParse` and `commonExtractorArgs.csvParse.options` are omitted from the config.
2. Ensure that options included in the config under `commonExtractorArgs.csvParse.options` are actually passed to the csv-parse module. This can be tested by including the following in your commonExtractorArgs:
```
"csvParse": {
   "options": {
      "to": 2
   }
 }
```
This instructs the `csv-parse` module to only parse CSV files up to the 2nd line, thus extracted bundles for any patients after patient 2 will be empty.

2022-01-20 17:49 UTC, dmendelowitz requested changes
This works great on all the extractors, but don't forget that `csvParse()` is also used in `appUtils.js` when parsing the patient ID CSV, that has messed us up in the past. Other than that, I had some small comments on the README and example config.

2022-01-20 17:49 UTC, dmendelowitz commented on README.md
> +The mCODE Extraction Framework uses the node `csv-parse` library to parse specified CSV files. [Parsing options for the `csv-parse` library](https://csv.js.org/parse/options/) can be included in the
And I think if the user puts a different value for one of the ones we use by default, it will overwrite our default with what the user put, which also might be worth noting in the README

2022-01-20 17:56 UTC, julianxcarter commented on config/csv.config.example.json
> +        "bom": true
Yeah I'm with you here actually I don't think this has a place in the example config now that I think about it. I put it in here because I wanted to illustrate how it's used, but I think we should leave that to the section in the README. Our usual guidance when setting up the MEF is "Take the example config, change the file name, and then add filePaths for your extractors" so it doesn't make sense to have an option that we don't want users using in there.

2022-01-20 17:57 UTC, julianxcarter commented on README.md
> +The mCODE Extraction Framework uses the node `csv-parse` library to parse specified CSV files. [Parsing options for the `csv-parse` library](https://csv.js.org/parse/options/) can be included in the
This is a good point, I'll make a note of that!

2022-01-20 18:20 UTC, julianxcarter commented on README.md
> +The mCODE Extraction Framework uses the node `csv-parse` library to parse specified CSV files. [Parsing options for the `csv-parse` library](https://csv.js.org/parse/options/) can be included in the
Addressed in `031e8fa`

2022-01-20 18:20 UTC, julianxcarter commented on config/csv.config.example.json
> +        "bom": true
Addressed in `031e8fa`

2022-01-21 14:47 UTC, dmendelowitz approved these changes

2022-01-21 14:48 UTC, merged