New fields added to cancer disease status
mcode/mcode-extraction-framework pull request #32
Opened 2020-09-08 17:43 UTC by julianxcarter

# Summary
Added support for an additional `observationStatus` field in the CancerDiseaseStatus extractor.
## New behavior
The extractor can now extract attributes for `observationStatus` and `diseaseStatusText`. It will no longer be able to extract a value for `dateRecorded`, per the example csv file. 
## Code changes
1. Added new example fields in `docs/cancer-disease-status.csv`.
2. Updated the Cancer Disease Status extractor to throw an error if `observationStatus` is omitted given that it is a mandatory attribute. Also updated the extractor to read in a display value for `diseaseStatus`, falling back to a lookup with the `diseaseStatus` code by way of the helper functions in `src/helpers/diseaseStatusUtils.js` if a display value is not included.
3. Updated the diseaseStatusText values in `src/helpers/diseaseStatusUtils.js`. They may have been updated since the extractor was first built, but the ones included in the file no longer matched up with the values on the [reference site](http://standardhealthrecord.org/guides/icare/mapping_guidance.html).
4. Updated all test cases to correlate with additions made to the extractor. Also, added a minimal viable test case that only passes in mandatory values to the template.
# Testing guidance
Should be tested with the updated base-icare-extraction-client.

2020-09-10 15:43 UTC, kjmahalingam requested changes
This is awesome! I have one quick comment and question inline, but otherwise this looks like awesome work that is in line with the required documentation.

2020-09-10 15:43 UTC, kjmahalingam commented on src/templates/CancerDiseaseStatus.ejs
> +  }, <% if (typeof evidence !== 'undefined' && evidence && evidence.length > 0) { %>
DM1: `undefined` in JavaScript evaluates to `false` in checks like this, so you don't need to actually add this `typeof evidence !== 'undefined'` here by my understanding. 

As a separate question, is there any change you made to this file (aside from DM1 above) that wasn't just reordering things in here? I can't see one so just want to confirm!

2020-09-10 17:22 UTC, julianxcarter commented on src/templates/CancerDiseaseStatus.ejs
> +  }, <% if (typeof evidence !== 'undefined' && evidence && evidence.length > 0) { %>
DM1: You're absolutely right! I began adding in `typeof <variable> !== 'undefined'` as a habit last week to insure that a reference error isn't thrown if any of the variables haven't been declared. All of the extractors do declare variables for each of the possible attributes (and just make them `null` if the attribute wasn't included on the CSV), but Dylan P and I thought it would be good to have that extra level of protection. It can be dropped though since we wouldn't ever run into that problem with the extractors as they're currently designed.

Also, there were no other changes made to the template, I just reordered some things. Everything was already included when I began :).

2020-09-10 17:27 UTC, kjmahalingam commented on src/templates/CancerDiseaseStatus.ejs
> +  }, <% if (typeof evidence !== 'undefined' && evidence && evidence.length > 0) { %>
DM1: Thanks for the clarification! If @Dtphelan1 is also fine with this change, that's okay with me; it's ultimately harmless. :) I do, however, think that you can just check for `evidence !== undefined` instead of doing the `typeof` check though.

2020-09-10 18:09 UTC, julianxcarter commented on src/templates/CancerDiseaseStatus.ejs
> +  }, <% if (typeof evidence !== 'undefined' && evidence && evidence.length > 0) { %>
DM1: Gotcha! I think I'll go ahead and remove it since it's not likely to be an error that we encounter.

2020-09-10 19:54 UTC, kjmahalingam approved these changes
Nice work!

2020-09-10 19:57 UTC, kjmahalingam requested changes
Err...sorry if I mislead you, but I guess some tests are actually now failing due to ReferenceErrors. :(

I think the check mentioned in DM1 can probably be re-implemented, since that resolves the issue. Sorry again!

2020-09-11 12:03 UTC, kjmahalingam approved these changes
Alright, just ran and tested it again, and I *actually definitively approve* now. Good work!

2020-09-11 20:08 UTC, Dtphelan1 commented
Just for record keeping: Julian and team talked today about how to ensure that the CDS extractors can support both the ICARE specific valueSystem codes as well as the generic mCODE codes. We've come up with a reasonable approach that is low lift, and will help realize the overall task. Looking forward to reviewing those addl. changes come next week! 👍

2020-09-14 12:46 UTC, kjmahalingam commented
After the changes, still approved here! A couple small notes on the other PR, but great work. :)

2020-09-14 13:12 UTC, Dtphelan1 commented on src/helpers/diseaseStatusUtils.js
> +function getDiseaseStatusDisplay(code, implementation = 'icare') {
DP - If we are going to use a default arg value here, we probably want it to be "mcode", but given how the if-else statement works I don't think we need a default value at all. This also applies to the block of code above in the `getDiseaseStatusCode` function. 😄

2020-09-14 13:15 UTC, Dtphelan1 commented on src/helpers/diseaseStatusUtils.js
> +/* eslint-disable no-else-return */
DP - If we want to avoid making es-lint unhappy, we might want to use a switch statement instead of an if-else block in the disease status lookup functions.

2020-09-14 13:16 UTC, Dtphelan1 commented on test/helpers/diseaseStatusUtils.test.js
> +const currentDiseaseStatusTextToCodeLookup = {
DP - probably want two local lookup tables here now, right? And we want to make sure that changing the implementation flag will change the output? We should add a function for that too.

2020-09-14 15:22 UTC, julianxcarter commented on src/helpers/diseaseStatusUtils.js
> +/* eslint-disable no-else-return */
DP - Switched to a switch statement in the most recent commit and made the default case reference the current lookup table, which addressed the preview comment as well. Es-lint is now pleased :).

2020-09-14 15:23 UTC, julianxcarter commented on test/helpers/diseaseStatusUtils.test.js
> +const currentDiseaseStatusTextToCodeLookup = {
DP - Added a new lookup table and new functional test in the most recent commit!

2020-09-14 20:07 UTC, Dtphelan1 commented on test/helpers/diseaseStatusUtils.test.js
>      });
DP - Super small, but in the body of this loop could we add a second expect statement - `expect(getDiseaseStatusCode(dsText)).toEqual(dsCode);`  - that ensures our default case works when there is no argument supplied?

2020-09-14 20:08 UTC, Dtphelan1 commented on test/helpers/diseaseStatusUtils.test.js
>      });
Ditto the the `getMcodeDiseaseStatusDisplay` test below

2020-09-14 20:08 UTC, Dtphelan1 commented
After those changes, I believe we should be all set to approve! 🎉

2020-09-15 11:22 UTC, kjmahalingam approved these changes
I’m still good to approve, nice work!

2020-09-15 12:29 UTC, Dtphelan1 commented on test/helpers/diseaseStatusUtils.test.js
>      });
@julianxcarter in case this notification slipped through your inbox last night 👍

2020-09-15 14:56 UTC, julianxcarter commented on test/helpers/diseaseStatusUtils.test.js
>      });
DP - Just pushed up a commit with these changes! 👍🏽

2020-09-15 15:32 UTC, Dtphelan1 approved these changes
Looks good - set to merge after you rebase! 😄

2020-09-15 19:07 UTC, merged