Observation extractor
mcode/mcode-extraction-framework pull request #35
Opened 2020-09-16 22:10 UTC by julianxcarter

# Summary
An Observation extractor has been added to the extraction framework.
## New behavior
The extraction framework is now capable of extracting data from a corresponding Observation csv, populating a proper FHIR bundle with this data, and exporting this bundle.
## Code changes
1. An example observation csv file has been added at `docs/observation.csv`.
2. A CSVObservationExtractor file has been added at `src/extractors/CSVObservationExtractor.js`.
3. The new `CSVObservationExtractor` module has been added to the import and export statements in both index files at `src/index.js` and `src/extractors/index.js`.
4. The file path for the new observation template has been added to the `fhirTemplateLookup` table in `src/helpers/ejsUtils.js`.
5. A file containing helper functions for the CSVObservationExtractor class has been added at `src/helpers/observationUtils.js`.
6. An observation template has been created at `src/templates/Observation.ejs`.
7. Tests for the CSVObservationExtractor module, helper functions, and template have been created within the `test` directory.
8. A mock observation bundle and module response have been added at `test/extractors/fixtures` for use in `CSVObservationExtractor.test.js`.
9. Mock generated resources have been added at `test/templates/fixtures`.
# Testing guidance
Must be run from the corresponding `observation-extractor` branch of the base ICARE client. The following steps must be followed within the `base-icare-extraction-client`:
1. Within `package.json`, change the value of `mcode-extraction-framework` to the file path of the local `mcode-extraction-framework` directory on your machine.

2. Perform an `npm install` to ensure that the base ICARE client is using the updated version of the `mcode-extraction-framework`.

3. Run the client as normal with the following command
  `node src/cli.js -p config/csv.config.json -f <from-date>`

2020-09-22 13:13 UTC, kjmahalingam requested changes
Looks awesome! A few notes in-line below.

I *still* for some reason cannot get my FHIR validator working, so I didn't run that locally. That said, the observations pass the AWS FHIR R4 validation when we send them up and I'm guessing that's all we need, since we're just checking base FHIR instead of mCODE. If someone else who tests wants to run the FHIR validator locally, though, just note that I didn't do that.

2020-09-22 14:01 UTC, julianxcarter commented on src/templates/Observation.ejs
> +  ], <%}else if (code.code === '39004-7') {%>
DM3: I only included the category attribute for the resource types that require it, namely Tumor Markers and Vital Signs. There are two other resources (ECOG and Karnofsky Performance Status) that include them as optional but have a different category code. If we want to include the category on those resources too, then I could use a general `else` case as you said and then check for `code.code` in the actual coding of the category.

2020-09-22 16:46 UTC, julianxcarter commented on src/helpers/observationUtils.js
> +const quantityCodeToUnitLookup = {
DM2: They're all listed on [this page listing all of the vital signs](http://hl7.org/fhir/R4/observation-vitalsigns.html) which is where I got them, unitsofmeasure.org is the given code system for them. I'll make the change!

2020-09-22 16:52 UTC, julianxcarter commented on test/helpers/observationUtils.test.js
> +const vitalSignsCodeToTextLookup = {
DM4: There's no reason for it! I just didn't think to export those objects, great suggestion.

2020-09-22 17:44 UTC, danlee1025 commented on src/extractors/CSVObservationExtractor.js
> +  async get({ mrn, fromDate, toDate }) {
@Dtphelan1 @jafeltra  Do we plan to filter csv observation data?

[DL1] I don't see the `dateRecorded` column in the csv so I'm assuming not thus we can remove the `fromDate` and `toDate` from this extractor.

2020-09-22 17:47 UTC, danlee1025 commented on src/extractors/CSVObservationExtractor.js
> +      throw new Error('The observation is missing an expected attribute. Obervation id, mrn, status, code, code system, value, value code system, and effective date are all required.');
[DL2] Small typo here in the string, should be Observation.

2020-09-22 18:03 UTC, danlee1025 commented on test/helpers/observationUtils.test.js
> +  test('isVitalSign,', () => {
[DL3] Test description should probably include something like "isVitalSign should return false when given a code that is not in vitalSignsCodeToTextLookup" or something like that just so it's easier to understand what the test is doing.

2020-09-22 19:08 UTC, julianxcarter commented on src/extractors/CSVObservationExtractor.js
> +  async get({ mrn, fromDate, toDate }) {
DL1: You're right that was superfluous. Neither the ticket or the csv detailing the extractor format mention date filtering so I'll go ahead and remove that.

2020-09-22 19:30 UTC, danlee1025 approved these changes
LGTM

2020-09-23 12:51 UTC, kjmahalingam commented on src/templates/Observation.ejs
> +  ], <%}else if (code.code === '39004-7') {%>
DM3: Sorry, just saw this! I noticed that you added an else to add a check for `survey` and I believe I remember now that we didn't feel the need to implement ECOG and Karnofsky. You can revert this to what it was previously, knowing that we don't need to include the category since it has a min of 0.

2020-09-23 15:28 UTC, kjmahalingam approved these changes
Great work!

2020-09-23 15:28 UTC, merged