Observation template revamp
mcode/mcode-extraction-framework pull request #43
Opened 2020-10-08 18:36 UTC by kjmahalingam

# Summary
Updates the Observation template to use the new templating approach.

## Code changes
- Removed the old `CarePlanWithReview.ejs` and replaced with the `CarePlanWithReviewTemplate.js`
- Flattened and changed the structure of the input arguments to the template in `CSVObservationExtractor.js`
- Add more to `observationUtils.js` to determine the type of Observation to process
- Move generic FHIR operations to `fhirUtils.js`
- Update `valueQuantity` check in `valueX.js`
- Update tests and fixtures

# Testing guidance
Ensure the tests pass and that the output of the `base-icare-extraction-client` (on its corresponding PR) succeeds and looks correct.

2020-10-09 14:43 UTC, kjmahalingam commented on src/templates/ObservationTemplate.js
> +  return null;
DM1 (me @ myself): Is returning null safe here? I assume that since we are spreading this operation later inside the context of an object, it will just result in no category being rendered, but I don't want there to be a random `null` hanging around so just clarifying.

2020-10-09 15:16 UTC, Dtphelan1 commented on src/templates/ObservationTemplate.js
> +
```suggestion
```

2020-10-09 15:32 UTC, jafeltra reviewed
I'm still reviewing, but this group of comments are all related to the discussion we had about using `code` vs `unit` for valueQuantities, so I wanted to leave them as a group. I'm going to continue reviewing the rest of this now!

2020-10-09 15:32 UTC, jafeltra commented on src/helpers/fhirUtils.js
> +const quantityCodeToUnitLookup = {
We talked about this lookup a bit at the working session. I think this is trying to map unit `codes` to the `unit` string representation of the codes. I'm not entirely sure if all the entries in this map are accurate or comprehensive. But after looking at the [Quantity](https://www.hl7.org/fhir/datatypes.html#Quantity) in FHIR, it looks like the unit is not required, so I think it might just be better to not manipulate the code at all, and instead just set it to the `code` field. If we do that though, I believe we'll have to set a `system` as well based on the constraint.

2020-10-09 15:32 UTC, jafeltra commented on src/helpers/fhirUtils.js
> +    return null;
If we do end up keeping the look up above, I think we should consider just returning the `unitCode` value here. I think it is better to preserve the potentially incorrect value provided rather than remove it. I think that's a pattern we've followed in other places in the framework as well.

2020-10-09 15:32 UTC, jafeltra commented on src/templates/snippets/valueX.js
> +            ...(quantMatch[6] && { unit: getQuantityUnit(quantMatch[6]) }),
Based on the comment I made above, I think we might want to set this matched "unit" value to the `code` on a quantity (see [Quantity](https://www.hl7.org/fhir/datatypes.html#Quantity)).

2020-10-09 15:32 UTC, jafeltra commented on src/templates/ObservationTemplate.js
> +  return valueX(valueCode); // Vital Sign will be parsed as quantity, others will be parsed as appropriate
I think we decided that we want quantities to default to using ucum (http://unitsofmeasure.org) as the `system` if one is not specified. I think this might be the place to do that since we'll know that a `valueQuantity` was returned here and we have access to the `valueSystem`.

2020-10-09 16:09 UTC, kjmahalingam commented on src/templates/ObservationTemplate.js
> +  return null;
We determined that this is safe, so I retract DM1 from myself.

2020-10-09 16:29 UTC, jafeltra reviewed
This looks really good! I just had a couple additional minor comments. Let me know if you disagree with any of them!

2020-10-09 16:29 UTC, jafeltra commented on test/helpers/observationUtils.test.js
> +  test('isKarnofskyPerformanceStatus should return false when passed a code that does not belong to a Vital Sign', () => {
I think there's an old reference to "Vital Sign" here

2020-10-09 16:29 UTC, jafeltra commented on test/helpers/observationUtils.test.js
> +  test('isECOGPerformanceStatus should return false when passed a code that does not belong to a Vital Sign', () => {
Similar to above,  I think there's an old reference to Vital Sign.

2020-10-09 16:29 UTC, jafeltra commented on test/templates/observation.test.js
>    });
I think we might want one additional test here that checks that all combinations of the optional fields can be passed into the template without it crashing. Similar to [this patient template test](https://github.com/mcode/mcode-extraction-framework/blob/master/test/templates/patient.test.js#L45).

2020-10-09 17:05 UTC, jafeltra approved these changes
This looks great! You've resolved all my comments!

2020-10-09 21:18 UTC, Dtphelan1 commented
Some additional reading of the FHIR materials on [Quantity](https://www.hl7.org/fhir/datatypes.html#Quantity), the [R4 Observation resource content](https://www.hl7.org/fhir/observation.html#resource) and examples of observations - both [Vitalsigns](https://www.hl7.org/fhir/observation-vitalsigns.html) and plain old [R4 Observations](https://www.hl7.org/fhir/observation-examples.html#) make me think that we want to include the `unit` field _as well as_ the  `code` field. Take a look at what I've linked and let me know if you disagree strongly with my reading.

2020-10-09 21:19 UTC, Dtphelan1 commented on src/helpers/ejsUtils.js
> +  cancerDiseaseStatusTemplate, carePlanWithReviewTemplate, conditionTemplate, observationTemplate, patientTemplate, researchStudyTemplate, researchSubjectTemplate,
Nice rearranging 👍

2020-10-09 21:21 UTC, Dtphelan1 commented
Bar my comment above re: `unit`, this looks good! (Though a fresh look on Monday morning may reveal something my haggard Friday eyes can't see...)

On that note - have a good weekend!

2020-10-12 14:49 UTC, julianxcarter requested changes
This looks and works great! Once my single comment is addressed I'll be ready to approve. 👍🏽

2020-10-12 14:49 UTC, julianxcarter commented on src/templates/snippets/valueX.js
> +            ...(quantMatch[6] && { code: quantMatch[6], system: 'http://unitsofmeasure.org' }),
JC 1: This looks good! The only thing that should be added to the return object is a `unit` property that seems to be a required value in the VitalSigns observations. An example can be seen [here](http://hl7.org/fhir/observation-example-head-circumference.json.html) under the `valueQuantity` element. The unit property is essentially just a display value for the `code` property, so we could restore the lookup table that used to be in `observationUtils` and include that here. Happy to chat more about this!

2020-10-12 16:42 UTC, julianxcarter commented on src/templates/snippets/valueX.js
> +            ...(quantMatch[6] && { code: quantMatch[6], system: 'http://unitsofmeasure.org' }),
JC 1 (cont.): Looks like @Dtphelan1 had the exact same comment so this is a bit redundant 😅.

2020-10-13 12:15 UTC, kjmahalingam commented
Addressing DP1 and JC1 since they're the same:

Thanks for checking on that! I could re-implement the quantity unit lookup that was implemented before, but in going to do that, I noticed this example.

https://www.hl7.org/fhir/observation-example-respiratory-rate.json.html

It looks like there's a "unit" here for `breaths/minute` that isn't in the map for the code we had originally written. I'm wondering where we got that initial list of units and their mappings, because I am concerned that it might not be complete and we may need to add more. Do @Dtphelan1 or @julianxcarter have any thoughts about this? I will re-implement what we have if that's what's needed, but I don't know if we'd be missing information as a result.

2020-10-13 14:13 UTC, kjmahalingam commented
@Dtphelan1 @julianxcarter The latest commit should address your concerns.

2020-10-13 14:17 UTC, julianxcarter approved these changes
This looks good to me! I've resolved my comment and approved, nice work :).

2020-10-13 18:12 UTC, jafeltra commented
This still looks good to me! I like the addition of the warning being logged and returning the unit code if the map doesn't provide a unit string.

2020-10-13 19:25 UTC, Dtphelan1 commented on src/helpers/fhirUtils.js
> +// value sets utilized by these Vital Signs
Nice.

2020-10-13 20:45 UTC, Dtphelan1 commented
lgtm

2020-10-13 20:45 UTC, Dtphelan1 approved these changes

2020-10-13 20:45 UTC, merged