Standardized empty data approach
mcode/mcode-extraction-framework pull request #58
Opened 2020-11-18 19:48 UTC by julianxcarter

# Summary
Standardizes the shape of empty data that's fed into the templates.  
## New behavior
A helper function has been introduced to `ResourceGenerator.js` which iterates through object properties and converts all `undefined` and empty string values to `null`.
## Code changes
* A `cleanEmptyData()` method has been added to `ResourceGenerator.js`.
* Unit tests for this method have been added to `resourceGenerator.test.js`.
* Manual empty data setting within each of the extractors has been removed, as they're no longer needed (unless the property in question is being formatted by a separate function such as `formatDateTime()`.
# Testing guidance
Ensure all tests pass, I also suggest manually setting a property to `undefined` or an empty string within one the `formatData()` method of one of the extractors, and then ensuring that the same property comes in to the corresponding template as a `null` value. Happy testing!

2020-11-19 19:38 UTC, Dtphelan1 commented on src/templates/ResourceGenerator.js
> +        }
DP1 - it looks like this only goes 2 layers deep in this check; should we have a recursive loop here?

2020-11-20 14:29 UTC, julianxcarter commented on src/templates/ResourceGenerator.js
> +        }
DP1- That'd absolutely be the safest and most inclusive to do here, I'll go ahead and make this recursive.

2020-11-20 14:50 UTC, jafeltra commented
This looks really good! I like this approach! Besides Dylan's one comment, the only other thought I had was about using this approach in the template tests. I'm not entirely sure if this is an approach we want to take, but I wanted to throw it out there to see what you and others think. Do you think it makes sense to set up the "minimal" data objects we create with the empty string/null/undefined values and use the `cleanEmptyData` function on those objects? I do think that your tests for the `cleanEmptyData` function test out the functionality appropriately, so I don't really know that this is necessary at all.

2020-11-23 16:03 UTC, Dtphelan1 commented on src/templates/ResourceGenerator.js
> +
Alright one last thing on the loop - JavaScript objects can contain circular references and infinite loops. Could we add a MAX_DEPTH parameter to this file, and make sure that we never go beyond a certain maximum depth size? We can then set the default depth parameter to 0, and make sure we increment the depth every time we make a recursive call.

2020-11-23 17:27 UTC, jafeltra commented
Okay after thinking about my comment again and talking to @julianxcarter a bit about it, I don't think we'll need to actually use the `cleanEmptyData` function in the template tests. But maybe we should set up the data that we pass into the templates in the tests in a way that assumes it's gone through the `cleanEmptyData` function already. I think the majority of the template tests already do this, but I at least noticed that the care plan template just leaves off the non-required data in the minimal data objects. I think we'd maybe want to have all the non-required data have a `null` value now, right? Git blame seems to be blaming me on this one, so if it helps, I can help out with this.

2020-11-23 18:02 UTC, julianxcarter commented on src/templates/ResourceGenerator.js
> +
I've added this to the most recent commit. I thought that 3 recursive calls was a good ceiling, but I can raise or lower that depending on what you think is appropriate!

2020-11-23 18:49 UTC, Dtphelan1 commented on src/templates/ResourceGenerator.js
> +      if (depth < MAX_DEPTH) cleanEmptyData(cleanData[element], depth + 1);
..... okay one last thing, and I mean it this time.

1) Could we make the max_depth something a little more generous, like 50? Hopefully this safeguard should only prevent infinite loops, and not stop us from traversing deep objects.
2) Could we log a warning message when we hit our max depth? Something indicating that we're trying to clean an empty object, hit a maximum recursive depth, and might not totally clean the object of empty values? 
3) Could we write a test case that ensures we halt execution when depths get too large? We could test that a nested object doesn't get changed when the depth is higher than the limit, and that it does when it's smaller. 

I promise I'll be more explicit next time I plan on being this needy 😄

2020-11-23 19:15 UTC, jafeltra reviewed
This looks good to me! I think your latest changes to the template tests make a lot of sense and will help us test if the templates are ever not working as we expect after we use the `cleanEmptyData` function! I didn't see anything else besides Dylan's last few comments, so I'm good to approve ones those are set!

2020-11-23 19:19 UTC, julianxcarter commented on src/templates/ResourceGenerator.js
> +      if (depth < MAX_DEPTH) cleanEmptyData(cleanData[element], depth + 1);
Yes to all three! I had a hunch that a limit of 3 may have been outrageously small so this isn't exactly a surprise. I'll push up these changes in the next commit :)

2020-11-24 18:42 UTC, Dtphelan1 commented
I feel pretty good about this!

2020-11-24 18:42 UTC, Dtphelan1 approved these changes

2020-11-24 20:18 UTC, Dtphelan1 requested changes
Alright. I'm no longer making promises about the future state of nitpickiness....

Here are some more comments I have after talking with Julia: 
1. We should write a test that explicitly checks that we can handle circular dependencies without failing or blowing the stack. Something like this?
```
  test('Handles circular references without crashing', () => {
    const obj = {};
    obj.obj = obj;
    expect(() => cleanEmptyData(obj)).not.toThrow();
  });
```
2. Instead of building a super-deep object, we could make a shallow one and just manually provide a `depth` argument that is >= than the MAX_DEPTH. Could be 50, 200, your choice. :smile: 
3. In our emptyData else loop, we have an additional clean step. I think we could probably get rid of that, right? When Jules and I were testing this function manually, we were kindof shocked that it cleaned up keys at layers deeper than MAX_DEPTH. 
4. When we loop over the data object's keys, we call each item we loop over an `element`. Could we rename that to `key`, like we do in our secondary loop around line 47/48?

2020-11-30 15:12 UTC, jafeltra approved these changes
This looks good to me! The latest changes address the last set of comments and I haven't noticed anything else!

2020-11-30 17:19 UTC, Dtphelan1 approved these changes
Thank you so much for your patience. This all looks very good to me 😄

2020-11-30 17:23 UTC, merged